name       : gpm
version    : 1.20.7
release    : 5
source     :
    - git|https://github.com/telmich/gpm.git : e82d1a653ca94aa4ed12441424da6ce780b1e530
homepage   : http://www.gnu.org/software/time
license    : GPL-1.0-only
summary    : gpm (General Purpose Mouse daemon)
component  : system.base
description: |
    GPM allows the use of a mouse in the console and xterm.
setup      : |
    %patch -p1 < $pkgfiles/0001-Support-a-stateless-configuration-for-Solus.patch
    %autogen.sh --disable-static
build      : |
    %make -j1
install    : |
    %make_install
    ln -sv $(readlink $installdir/%libdir%/libgpm.so.2) $installdir/%libdir%/libgpm.so
    for item in gpm-root.conf gpm-syn.conf gpm-twiddler.conf ; do
        install -D -m 00644 $pkgfiles/${item} $installdir/usr/share/defaults/gpm/${item}
    done
    rmdir $installdir/etc
