name        : gpm
version     : 1.20.7
release     : 2
source      :
    - http://www.nico.schottelius.org/software/gpm/archives/gpm-1.20.7.tar.gz : c7e4661c24e05ae13547176b649bac8e3a0db2575f7dd57559f9e0b509f90f49
homepage    : http://www.gnu.org/software/time
license     :
    - GPL-1.0
summary     : gpm (General Purpose Mouse daemon)
component   : system.base
description : |
    GPM allows the use of a mouse in the console and xterm.
setup      : |
    %patch -p1 < $pkgfiles/0001-Support-a-stateless-configuration-for-Solus.patch
    %autogen --disable-static
build      : |
    %make -j1
install    : |
    %make_install
    ln -sv $(readlink $installdir/%libdir%/libgpm.so.2) $installdir/%libdir%/libgpm.so
    for item in gpm-root.conf gpm-syn.conf gpm-twiddler.conf ; do
        install -D -m 00644 $pkgfiles/${item} $installdir/usr/share/defaults/gpm/${item}
    done
